(function (global) {
  "use strict";
  const NAME="HydroSHEDSFlowAccumulationAdapterV32", VERSION="FORECAST-1J6G2.0";
  const META_URL="data/hydrology/saudi_hydrosheds_acc_15s.meta.json";
  const DATA_URL="data/hydrology/saudi_hydrosheds_acc_15s.u32";
  let cache=null;
  const rad=x=>x*Math.PI/180;
  function distanceKm(a,b,c,d){const R=6371,p1=rad(a),p2=rad(c),dp=rad(c-a),dl=rad(d-b);const q=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.asin(Math.sqrt(q));}
  async function load(){if(cache)return cache; const meta=await fetch(META_URL,{cache:"force-cache"}).then(r=>{if(!r.ok)throw Error("ACC metadata HTTP "+r.status);return r.json();}); const res=await fetch(DATA_URL,{cache:"force-cache"}); if(!res.ok)throw Error("ACC data HTTP "+res.status); if(!global.DecompressionStream)throw Error("DecompressionStream unsupported"); const ab=await new Response(res.body.pipeThrough(new DecompressionStream("gzip"))).arrayBuffer(); const values=new Uint32Array(ab); if(values.length!==meta.width*meta.height)throw Error("ACC raster size mismatch"); cache={meta,values}; return cache;}
  function cell(meta,lat,lon){const col=Math.floor((lon-meta.left)/meta.pixelWidth),row=Math.floor((meta.top-lat)/meta.pixelHeight);return {row,col};}
  function valueAt(ds,row,col){const {meta,values}=ds;if(row<0||col<0||row>=meta.height||col>=meta.width)return null;const v=values[row*meta.width+col];return v===meta.nodata?null:v;}
  async function evaluateCity(city,options={}){const lat=Number(city?.lat??city?.latitude),lon=Number(city?.lon??city?.longitude);if(!Number.isFinite(lat)||!Number.isFinite(lon))throw Error("Valid city coordinates required");const radiusKm=Number.isFinite(+options.radiusKm)?+options.radiusKm:3;const ds=await load(),{meta}=ds,c=cell(meta,lat,lon);const dLat=radiusKm/111.32,dLon=radiusKm/(111.32*Math.max(.1,Math.cos(rad(lat))));const rr=Math.ceil(dLat/meta.pixelHeight),cc=Math.ceil(dLon/meta.pixelWidth);let max=-1,best=null,valid=0;for(let r=c.row-rr;r<=c.row+rr;r++){const y=meta.top-(r+.5)*meta.pixelHeight;for(let k=c.col-cc;k<=c.col+cc;k++){const x=meta.left+(k+.5)*meta.pixelWidth;const d=distanceKm(lat,lon,y,x);if(d>radiusKm)continue;const v=valueAt(ds,r,k);if(v==null)continue;valid++;if(v>max){max=v;best={latitude:+y.toFixed(6),longitude:+x.toFixed(6),distanceKm:+d.toFixed(3),acc:v,row:r,col:k};}}}const center=valueAt(ds,c.row,c.col);const ok=!!best;return {engine:NAME,version:VERSION,status:ok?"REAL_DRAINAGE_CONTEXT_READY":"REAL_DRAINAGE_CONTEXT_UNAVAILABLE",city:city?.nameAr||city?.name||city?.nameEn||null,coordinates:{lat,lon},searchRadiusKm:radiusKm,centerAcc:center,maxAcc:ok?best.acc:null,strongestCell:best,validCells:valid,source:{provider:"HydroSHEDS",product:"Flow Accumulation (ACC)",resolutionArcSeconds:meta.resolutionArcSeconds,sourceFile:meta.sourceFile,syntheticData:false},interpretation:{metric:"upstream accumulated grid-cell count",municipalDrainageCapacity:false,confirmedFloodPrediction:false},syntheticData:false};}
  const api={name:NAME,version:VERSION,evaluateCity,getStatus:()=>({name:NAME,version:VERSION,realDataRequired:true,syntheticDataAllowed:false,municipalDrainageCapacity:false})};
  global.HydroSHEDSFlowAccumulationAdapterV32=api;global.RG32=global.RG32||{};global.RG32.HydroSHEDSFlowAccumulationAdapter=api;
  console.log(`[RainGuard] ${NAME} ${VERSION} loaded`);
})(window);
